### ISSUE TITLE
Missing instructions how to run

### ISSUE THREAD

**Issue by gurghet** [co0p/goNurseSchedulingSolver#1]
I’m not very familiar with go but I could not make this run. There is no instructions on how this is supposed to run. I am thinking something like this: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
Particularly the "getting started" section

**Comment by co0p** [comment]
Hey Andrea

It is still wip - so don't get your hopes up. I will put a wip badge on the
repo.

My goal is to get a demo running and slowly implement other restrictions
such as holidays, working hours etc...

Best regards, julian

Andrea Passaglia <notifications@github.com> schrieb am So., 14. Juni 2020,
20:11:

**Comment by co0p** [comment]
Added wip badge

**Comment by gurghet** [comment]
Oh, I’m so sorry, I just noticed the commit date! It’s funny I decided to review all nurse problem solvers today. Thanks!

**Comment by co0p** [comment]
Cool. Please leave a link to any publication or document that lists them. I
may interested as well !

Andrea Passaglia <notifications@github.com> schrieb am So., 14. Juni 2020,
22:07:

**Comment by gurghet** [comment]
I can share what I have, but probably not here, do you have an email?
